services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    image: webapp
    container_name: webapp
    restart: unless-stopped
    ports:
      - 3000:3000 # web
      - 5555:5555 # prisma studio
    environment:
      DATABASE_URL: ${DATABASE_URL_EXTERNAL}
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./package.json
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db-data:
