FROM node:alpine3.20
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

WORKDIR /usr/src/app

COPY package*.json .
COPY pnpm-lock.yaml .

RUN pnpm install 

COPY . .

EXPOSE 3000

ENTRYPOINT [ "./scripts/entrypoint.sh" ]